### ISSUE TITLE
Error 403 (blocked) in the middle of a course

### ISSUE THREAD

**Issue by Bigemul** [rojter-tech/pluradl.py#39] opened 2020-04-14 05:45 UTC
Hi everyone,

As some people here, I got the error 403. In my case, it happened in the middle of the course. The first message was different from the next ones. The first one didn't find the 86th video of a course.

I copied the logs of when the error appeared. Before that error, everything was normal.

```
[download] Sleeping 208.50 seconds...
[download] Destination: 085-10-Object-Oriented_Design_with_Function_Objects-1280x720.mp4

[K[download]   0.0% of 6.79MiB at 521.36KiB/s ETA 00:13

[K[download]   0.0% of 6.79MiB at 773.38KiB/s ETA 00:09

[K[download]   0.1% of 6.79MiB at 842.74KiB/s ETA 00:08

[K[download]   0.2% of 6.79MiB at 751.58KiB/s ETA 00:09

[K[download]   0.4% of 6.79MiB at 885.46KiB/s ETA 00:07

[K[download]   0.9% of 6.79MiB at 863.06KiB/s ETA 00:07

[K[download]   1.8% of 6.79MiB at 931.41KiB/s ETA 00:07

[K[download]   3.7% of 6.79MiB at 937.12KiB/s ETA 00:07

[K[download]   7.4% of 6.79MiB at 956.98KiB/s ETA 00:06

[K[download]  14.7% of 6.79MiB at 952.99KiB/s ETA 00:06

[K[download]  28.4% of 6.79MiB at 960.88KiB/s ETA 00:05

[K[download]  42.3% of 6.79MiB at 972.60KiB/s ETA 00:04

[K[download]  56.7% of 6.79MiB at 974.64KiB/s ETA 00:03

[K[download]  70.8% of 6.79MiB at 975.64KiB/s ETA 00:02

[K[download]  84.9% of 6.79MiB at 975.33KiB/s ETA 00:01

[K[download]  98.9% of 6.79MiB at 974.98KiB/s ETA 00:00

[K[download] 100.0% of 6.79MiB at 976.13KiB/s ETA 00:00

[K[download] 100% of 6.79MiB in 00:07
[download] Downloading video 86 of 104
[pluralsight] 47b1b923-f25c-4905-8e74-1ff976fb1728-11: Downloading JSON metadata
[pluralsight] 47b1b923-f25c-4905-8e74-1ff976fb1728-11: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 47b1b923-f25c-4905-8e74-1ff976fb1728-11: Downloading mp4-high-widescreen viewclip JSON
Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] 47b1b923-f25c-4905-8e74-1ff976fb1728-11: Waiting for 5 seconds to avoid throttling
[0;31mERROR:[0m No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/my_name/Downloads/pluradl.py-master y/plura_dl/PluraDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Users/my_name/Downloads/pluradl.py-master y/plura_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/my_name/Downloads/pluradl.py-master y/plura_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/Users/my_name/Downloads/pluradl.py-master y/plura_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
plura_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.

Something went wrong.
The download request for 'getting-started-python-core' was forced to terminate.
Double check that https://app.pluralsight.com/library/courses/getting-started-python-core
exists or that your subscription is valid for accessing its content.

Moving content to /Users/my_name/Downloads/pluradl.py-master y/courses/_failed/getting-started-python-core
```

In case you're wondering, the "y" doesn't stand for "this is the 25th instance". This was the second of three instances (with three different accounts) and the two others are working pretty well. When I went to Pluralsight, the site showed me "Your account has been blocked due to suspicious activity."

**Comment by Taranis01** [comment] 2020-04-14 13:37
duplicate of #38

**Comment by rojter-tech** [comment] 2020-04-14 20:22
> duplicate of #38

no, this issue is due to the account getting banned, #38 is due to subscription issues

**Comment by fortunewalla** [comment] 2020-04-15 09:37
The tool works perfectly. The website security is very sensitive to usage.

* Don't use the script and website at the same time.
* Don't use many instances of the script. Only one script run at a time.
* Keep a gap of at least 30-45min between each course download. 
* Spread your usage throughout the day.
* Better to complete a course on website and then after 1 hour use the script to download. This shows up you are reviewing the course again.

All the best!

**Comment by shawn8888** [comment] 2020-04-15 15:18
the tools still works. 
I got 403 error but works after switch to a new IP. Obviously, SP banned my old IP.

**Comment by Nocxy** [comment] 2020-04-16 17:19
Wouldn't downloader last longer if sleep time were higher, e.g. between between 100 and 300 seconds ? Wouldn't it allow more instances to run at the same time?

**Closed as completed** 2020-04-27 23:44 UTC
